# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install tzdata for timezone support
RUN apt-get update \
    && apt-get install -y --no-install-recommends tzdata \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml README.md ./
COPY src ./src

# Install build backend and package
RUN pip install --no-cache-dir hatchling \
 && pip install --no-cache-dir .

# Ensure stdout is unbuffered
ENV PYTHONUNBUFFERED=1

# Default command to run the MCP server
CMD ["mcp-timeserver"]
