# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.12-slim

# Ensure tzdata for zoneinfo
RUN apt-get update && apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project metadata
COPY pyproject.toml README.md ./
# Copy source code
COPY src ./src

# Install the package
RUN pip install --no-cache-dir .

# Entry point for MCP-timeserver
ENTRYPOINT ["mcp-timeserver"]
